### ISSUE TITLE
Fog looks weird under lava

### ISSUE THREAD

**Issue by eldeiibid** [devendrn/newb-shader-mcbe#8]
![Screenshot_20220206_124731_com mojang minecraftpe](https://user-images.githubusercontent.com/99124069/152679802-d8aee485-00da-4029-bfa2-027b6ea6e906.jpg)

**Comment by devendrn** [comment]
The issue has been fixed in 1d7c24e
However the new fog color doesn't blend perfectly with void. Fixing this seems unnecessary for now as it would require modification of various parts of the shader.
